### PR TITLE
polkadot v1.12.0

### PR DESCRIPTION
**Pull request by clangenb**
## Noteworthy changes 
* Update benchmarking macro. I essentially integrated the changes from: https://github.com/paritytech/polkadot-sdk/pull/3934/.
* Add `Preservation` arg to burn function in fungible trait
* Add `XcmRecorder` to `XcmConfig` for mocks

I would be very happy if this is released soon on crates.io ;)

### CODE REVIEW

**Comment by zjb0807** [comment]
Please update https://github.com/open-web3-stack/open-runtime-module-library/blob/master/Cargo.dev.toml to use polkadot-sdk v1.12.0

**Comment by clangenb** [comment]
I see that the coverage workflow failed due to the rate limit. Can we merge it like this?

**Comment by zjb0807** [comment]
> I could have noticed this earlier if the CI ran. I am wondering: as this isn't my first contribution, and neither my last. Is it possible to make the CI run with my PRs automatically?

This should be a GitHub setting. But it seems to run automatically.

> I see that the coverage workflow failed due to the rate limit. Can we merge it like this?

The coverage is not required. It's fine.

**Comment by clangenb** [comment]
Alright I see. I thought that I read that it needs a maintainer to run the action.

Cool, thanks a lot!

**Review by xlc — APPROVED** [review]

**Pull request merged**
